Desc/Asc last viewed date
xbapps/xbvr pull request #392
Opened 2020-12-07 21:45 UTC by yep-it-not-me

Changes "Recently viewed" sorting option into two Desc/Asc "Last viewed date" options, consistent with other sorting options. Now folks can pick whatever they watched forever ago!

2020-12-07 21:47 UTC, yep-it-not-me commented
Apologies for the extra commits, I'm working on windows and vscode, stuff I've never used for dev before. I'm also new to go.

2021-01-11 14:15 UTC, SpedNSFW requested changes

2021-01-11 14:15 UTC, SpedNSFW commented on ui/src/views/scenes/Filters.vue
> +            <option value="last_opened">↓ {{$t("Last viewed date")}}</option>
Since you're adding a second sort order, you should keep with the pattern and add the `_desc` suffix here.

2021-01-26 05:18 UTC, closed without merging

2021-01-26 05:19 UTC, yep-it-not-me commented
Closed because I couldn't figure out how to get github to update an existing PR ..

2021-01-26 05:21 UTC, SpedNSFW commented
> Closed because I couldn't figure out how to get github to update an existing PR ..

Just push to the branch. Same way you got the `_desc` commit here.
[`07bea1c` (#392)](https://github.com/xbapps/xbvr/pull/392/commits/07bea1c21aa9938d0d5528c553e2c338bcb6a755)